# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Froststrap.Froststrap
PackageVersion: 2.0.3
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallerSwitches:
  Silent: /S
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{8DC8A085-7E29-4D80-8D6A-69CD64913843}'
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- ProductCode: '{8DC8A085-7E29-4D80-8D6A-69CD64913843}'
  UpgradeCode: '{FE14203C-850D-5F78-8428-982AEDC74A3D}'
InstallationMetadata:
  DefaultInstallLocation: Froststrap
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Froststrap/Froststrap/releases/download/v2.0.3/Froststrap-windows-x64.msi
  InstallerSha256: E34951004D0E084BEF94A2B33B605F2A1AF7163F30C5F0CEE29157F0B0772CD6
ManifestType: installer
ManifestVersion: 1.12.0
